#!/usr/bin/env bash
# Installs nginx server
apt-get update
apt-get -y install nginx
# Create a default index.html file
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

# Replace the default nginx configuration
sudo sed -i 's|336182-web-01 localhost;|336182-web-01;|' /etc/nginx/sites-available/default

# Restart nginx without using systemctl
sudo /etc/init.d/nginx restart
