#!/usr/bin/env bash

#install and configure HAProxy on lb-01 server

sudo apt-get -y update
apt-get -y install haproxy


server_config=\
"
frontend  ayo-frontend
        bind *:80
        mode http
        default_backend amine-backend
backend ayo-backend
        balance roundrobin
        server 336182-web-01 54.236.43.72  check
        server 336182-web-02 54.160.70.33 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
