#!/usr/bin/env bash
# Print number 1-2 but display additional infomation on 4th 9th and 17th iteration

num=1
while ((num <= 20))
do
    echo $num
    case $num in
    "4")
        echo  "bad luck from China"
        ;;
    "9")
        echo  "bad luck from Japan"
        ;;
    "17")
        echo  "bad luck from Italy"
        ;;
    esac
    ((num++))
done
