#!/usr/bin/env bash
# Print hours from 0-12 and minutes from 1-59

hour=0
while (($hour <= 12))
do
	echo "Hour: $hour"
	minute=0
	while (($minute <= 59))
	do
		echo $minute
		((minute++))
	done
	((hour++))
done
